apiVersion: apps/v1
kind: Deployment
metadata:
  name: olm-operator
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: olm-operator
  template:
    metadata:
      labels:
        app: olm-operator
    spec:
      volumes:
        - name: srv-cert
          secret:
            secretName: olm-operator-serving-cert
        - name: client-ca
          secret:
            secretName: olm-profile-collector
        - name: kubeconfig
          secret:
            secretName: service-network-admin-kubeconfig
      containers:
        - name: olm-operator
          volumeMounts:
            - name: srv-cert
              mountPath: "/srv-cert"
              readOnly: true
            - name: client-ca
              mountPath: "/client-ca"
              readOnly: true
            - mountPath: /etc/openshift/kubeconfig
              name: kubeconfig
              readOnly: true
          command:
            - /bin/olm
          args:
            - --namespace
            - $(OPERATOR_NAMESPACE)
            - --writeStatusName
            - operator-lifecycle-manager
            - --writePackageServerStatusName=""
            - --tls-cert
            - /srv-cert/tls.crt
            - --tls-key
            - /srv-cert/tls.key
            - --client-ca
            - /client-ca/tls.crt
          image: OLM_OPERATOR_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
              name: metrics
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
          terminationMessagePolicy: FallbackToLogsOnError
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: olm-operator
            - name: RELEASE_VERSION
              value: RELEASE_VERSION
            - name: KUBECONFIG
              value: /etc/openshift/kubeconfig/kubeconfig
          resources:
            requests:
              cpu: 10m
              memory: 160Mi
